name: Spark CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Choose the appropriate Java version based on your Spark setup
        distribution: 'adopt'

    - name: Set up Spark
      run: | 
        wget https://dlcdn.apache.org/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.tgz
        tar xzf spark-3.4.1-bin-hadoop3.tgz
        
        export SPARK_HOME=$(pwd)/spark-3.4.1-bin-hadoop3
        export PATH=$PATH:$SPARK_HOME/bin
        spark-submit --version

    
    - name: PWD
      run: |
        ls

    - name: Build and Test Spark Code
      run: |
        cd Custom_folder
        spark-submit word_count.py
